### PR TITLE
code: define create user function

### PR DESCRIPTION
**Pull request by GideonBature**
Creates a `createAccount` function to the contract, allowing users to create new accounts by providing a shipping address. 

**It includes:**

1. Validation:

- Ensures the shipping address is not empty.
- Prevents account creation if one already exists for the caller.

2. Functionality:

- Initializes a new User struct with the provided shipping address and sets totalBuys to 0.

### CODE REVIEW

**Comment by OkoliEvans** [comment]
Can you add a test for this pls, the code is okay but adding a test is just to maintain standard

**Comment by GideonBature** [comment]
Definitely, will add a test latest this night. Thank you for the prompt response.

**Comment by GideonBature** [comment]
I have added test for create user account, create user account with empty address and also the one for duplicate user account...

I don't know if there is any other edge case I haven't touch that is necessary for the create user account function.

**Comment by OkoliEvans** [comment]
This is amazing, thank you for the job @GideonBature

**Pull request merged**
